# Generated by Django 5.1.3 on 2024-12-11 07:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_rename_is_feacherd_blogs_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='short_description',
            field=models.TextField(),
        ),
    ]
