# Generated by Django 5.1.3 on 2025-01-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_authorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
    ]
