# Generated by Django 5.1.3 on 2025-01-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
