# Generated by Django 5.1.3 on 2024-12-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_category_category_name'),
        ('userprofile', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(related_name='profiles', to='blogs.category'),
        ),
    ]
