# Generated by Django 5.1.3 on 2024-12-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_picture_alter_profile_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
